### ISSUE TITLE
Only some styles being applied

### ISSUE THREAD

**Issue by matt-koevort** [wagerfield/storybook-tailwind#1]
Hello @wagerfield 👋 

Thanks for building this out, came across @tailwind/jit yesterday and came across the same issues as you did. Your repro here has got my storybook up and running again which is great.

Less of an issue, and more of a question - the styles being applied in my stories are quite strange now. Colors and spacing do not seem to be applied anymore. Was wondering if you noticed anything similar? I'm assuming this is an issue with what is actually being output by the tailwind compiler.

**Comment by matt-koevort** [comment]
I retract my question 🙂 

Turns out we are calculating the styles in some of our React components using string template literals - which I am now discovering is a no-no according to the [docs](https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html)

**Comment by wagerfield** [comment]
https://tailwindcss.com/docs/optimizing-for-production#writing-purgeable-html

**Comment by wagerfield** [comment]
That's correct, yes. Follow that guide and you shouldn't have any issues.
